name: build executable file
on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          architecture: 'x64'
          cache: 'pip'

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Build Executable with Nuitka
        uses: Nuitka/Nuitka-Action@main
        with:
          nuitka-version: main
          script-name: main.pyw
          mode: onefile
          low-memory: true
          mingw64: true
          enable-plugins: tk-inter
          # 包含代码依赖包
          include-package: |
            UnityPy
            UnityPy.resources
            UnityPy.classes
            PIL
            tkinterdnd2
          # 包含依赖包的数据文件
          include-package-data: |
            UnityPy
            PIL
            tkinterdnd2
            archspec
          output-dir: build
          output-file: "BA-Modding-Toolkit.exe"
          assume-yes-for-downloads: true

      # 复制外部资源文件夹到 build 目录，与 exe 并列
      - name: Copy External Resources
        run: |
          Copy-Item -Path "locales" -Destination "build/locales" -Recurse
          Copy-Item -Path "assets" -Destination "build/assets" -Recurse
        shell: powershell

      # 上传 Artifact (方便调试)
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: BA-Modding-Toolkit-Windows-Build
          path: build/

      # 打包成 Zip (包含 exe + 外部文件夹)
      - name: Zip Release Asset (When Trigger With Tag)
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          $tag_name = "${{ github.ref_name }}"
          # 进入 build 目录打包所有内容
          cd build
          Compress-Archive -Path * -DestinationPath "../BA-Modding-Toolkit-$tag_name.zip"
        shell: powershell

      # 上传 Zip
      - name: Upload Release Asset (When Trigger With Tag)
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: BA-Modding-Toolkit-${{ github.ref_name }}.zip